package infrastructure

import (
	"reflect"
	"testing"

	"github.com/lividlabs/codefall-cli/cli/internal/initcmd/internal/application"
)

// fixture is the changelog's real shape: a hand-written preamble, releases newest first, a release
// with two breaking changes, releases with none, and one whose section sits between other sections.
const fixture = `# Changelog

Releases from 0.1.2 onward are generated by release-please from Conventional Commits.

## [0.19.0](https://github.com/lividlabs/codefall-cli/compare/v0.18.0...v0.19.0) (2026-09-24)


### Features

* **skills:** amend upstream documents ([#119](https://github.com/lividlabs/codefall-cli/issues/119)) ([bda33d2](https://github.com/lividlabs/codefall-cli/commit/bda33d2))

## [0.17.0](https://github.com/lividlabs/codefall-cli/compare/v0.16.0...v0.17.0) (2026-09-24)


### ⚠ BREAKING CHANGES

* **skills:** codefall-conceptualize is now codefall-envision, and the documents it writes moved.
* **skills:** the Beads section of a project's AGENTS.md now says to commit on the work's branch.

### Features

* **skills:** land every writing verb on a branch ([#107](https://github.com/lividlabs/codefall-cli/issues/107)) ([d84f23a](https://github.com/lividlabs/codefall-cli/commit/d84f23a))

## [0.16.0](https://github.com/lividlabs/codefall-cli/compare/v0.15.1...v0.16.0) (2026-09-22)


### Features

* **refresh:** let an agent invoke codefall-refresh on its own ([#105](https://github.com/lividlabs/codefall-cli/issues/105)) ([cc183dd](https://github.com/lividlabs/codefall-cli/commit/cc183dd))

## [0.13.0](https://github.com/lividlabs/codefall-cli/compare/v0.12.0...v0.13.0) (2026-09-16)

### ⚠ BREAKING CHANGES

* **init:** ` + "`--github-repo`" + ` is now ` + "`--issues-repo`" + `; there are no aliases and no migration.

### Refactoring

* **init:** rename the GitHub tracker flags ([#66](https://github.com/lividlabs/codefall-cli/issues/66)) ([f82cadf](https://github.com/lividlabs/codefall-cli/commit/f82cadf))

## 0.1.1

Hand-written. No sections here.
`

func TestBreakingChangesReadsTheSectionsReleasePleaseWrites(t *testing.T) {
	got, err := NewChangeLogSource([]byte(fixture)).BreakingChanges()
	if err != nil {
		t.Fatalf("BreakingChanges: %v", err)
	}

	want := []application.BreakingRelease{
		{Version: "0.17.0", Notes: []string{
			"**skills:** codefall-conceptualize is now codefall-envision, and the documents it writes moved.",
			"**skills:** the Beads section of a project's AGENTS.md now says to commit on the work's branch.",
		}},
		{Version: "0.13.0", Notes: []string{
			"**init:** `--github-repo` is now `--issues-repo`; there are no aliases and no migration.",
		}},
	}

	if !reflect.DeepEqual(got, want) {
		t.Errorf("BreakingChanges() =\n%+v\nwant\n%+v", got, want)
	}
}

// A section with no bullets under it recorded nothing, and text under another heading is not a
// breaking change however it is spelled.
func TestBreakingChangesIgnoresWhatIsNotABulletUnderTheHeading(t *testing.T) {
	text := "## [1.0.0](x) (2026-01-01)\n\n### ⚠ BREAKING CHANGES\n\n### Features\n\n* **a:** not breaking\n\n" +
		"## [0.9.0](x) (2025-12-01)\n\n### Bug Fixes\n\n* ⚠ BREAKING CHANGES mentioned in a fix\n"

	got, err := NewChangeLogSource([]byte(text)).BreakingChanges()
	if err != nil {
		t.Fatalf("BreakingChanges: %v", err)
	}

	if len(got) != 0 {
		t.Errorf("BreakingChanges() = %+v, want none", got)
	}
}

func TestBreakingChangesOnAnEmptyChangelog(t *testing.T) {
	got, err := NewChangeLogSource(nil).BreakingChanges()
	if err != nil || len(got) != 0 {
		t.Errorf("BreakingChanges() = %+v, %v, want none and no error", got, err)
	}
}
